contribution:
  - changed-files:
      - any-glob-to-any-file:
          - "submissions/examples/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"

core:
  - changed-files:
      - any-glob-to-any-file:
          - "core/**"